Repository Skhuthon/Skhuthon_0th_TEAM01_BE, pull requests merged in 2024-06, with the labels that each got.

#2 [feat] 회원 기능 구현
  build.gradle
  src/main/java/com/skhuthon/caffeinebalance/auth/config/CorsMvcConfig.java
  src/main/java/com/skhuthon/caffeinebalance/auth/config/SecurityConfig.java
  src/main/java/com/skhuthon/caffeinebalance/auth/config/SwaggerConfig.java
  src/main/java/com/skhuthon/caffeinebalance/auth/controller/MainController.java
  src/main/java/com/skhuthon/caffeinebalance/auth/dto/CustomOAuth2User.java
  src/main/java/com/skhuthon/caffeinebalance/auth/dto/GoogleResponse.java
  src/main/java/com/skhuthon/caffeinebalance/auth/dto/NaverResponse.java
  src/main/java/com/skhuthon/caffeinebalance/auth/dto/OAuth2Response.java
  src/main/java/com/skhuthon/caffeinebalance/auth/jwt/JWTFilter.java
  src/main/java/com/skhuthon/caffeinebalance/auth/jwt/JWTUtil.java
  src/main/java/com/skhuthon/caffeinebalance/auth/oauth2/CustomSuccessHandler.java
  src/main/java/com/skhuthon/caffeinebalance/auth/service/CustomOAuth2UserService.java
  src/main/java/com/skhuthon/caffeinebalance/user/domain/Role.java
  src/main/java/com/skhuthon/caffeinebalance/user/domain/SocialType.java
  src/main/java/com/skhuthon/caffeinebalance/user/domain/User.java
  src/main/java/com/skhuthon/caffeinebalance/user/dto/request/UserCreateRequestDTO.java
  src/main/java/com/skhuthon/caffeinebalance/user/dto/response/UserResponseDTO.java
  src/main/java/com/skhuthon/caffeinebalance/user/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: feature, setting

#9 [bug] 사용자 키, 몸무게 수정 안되는 버그 수정
  src/main/java/com/skhuthon/caffeinebalance/auth/config/CorsMvcConfig.java
  src/main/java/com/skhuthon/caffeinebalance/auth/config/SecurityConfig.java
  src/main/java/com/skhuthon/caffeinebalance/auth/config/SwaggerConfig.java
  src/main/java/com/skhuthon/caffeinebalance/user/controller/UserController.java
  src/main/java/com/skhuthon/caffeinebalance/user/domain/User.java
  src/main/java/com/skhuthon/caffeinebalance/user/dto/request/UserCreateRequestDTO.java
  src/main/java/com/skhuthon/caffeinebalance/user/dto/request/UserHeightWeightRequestDTO.java
  src/main/java/com/skhuthon/caffeinebalance/user/dto/response/UserHeightWeightResponseDTO.java
  src/main/java/com/skhuthon/caffeinebalance/user/dto/response/UserResponseDTO.java
  src/main/java/com/skhuthon/caffeinebalance/user/repository/UserRepository.java
  src/main/java/com/skhuthon/caffeinebalance/user/service/UserService.java
Labels: feature, chore, refactor, bug

#11 [chore] 필요없는 import문 제거
  src/main/java/com/skhuthon/caffeinebalance/auth/config/SecurityConfig.java
  src/main/java/com/skhuthon/caffeinebalance/user/controller/UserController.java
  src/main/java/com/skhuthon/caffeinebalance/user/dto/request/UserCreateRequestDTO.java
  src/main/java/com/skhuthon/caffeinebalance/user/dto/response/UserHeightWeightResponseDTO.java
  src/main/java/com/skhuthon/caffeinebalance/user/dto/response/UserResponseDTO.java
Labels: chore

#14 [fix] redirect url 변경
  src/main/java/com/skhuthon/caffeinebalance/auth/config/SecurityConfig.java
  src/main/java/com/skhuthon/caffeinebalance/auth/oauth2/CustomSuccessHandler.java
  src/main/resources/application.yml
Labels: chore

#25 [feat] customException 추가
  src/main/java/com/skhuthon/caffeinebalance/exception/CustomException.java
  src/main/java/com/skhuthon/caffeinebalance/exception/CustomExceptionHandler.java
  src/main/java/com/skhuthon/caffeinebalance/exception/ErrorCode.java
  src/main/java/com/skhuthon/caffeinebalance/exception/ErrorResponse.java
Labels: feature

#26 [feat] 상품 페이지 기능 구현
  src/main/java/com/skhuthon/caffeinebalance/auth/controller/MainController.java
  src/main/java/com/skhuthon/caffeinebalance/auth/dto/NaverResponse.java
  src/main/java/com/skhuthon/caffeinebalance/auth/service/CustomOAuth2UserService.java
  src/main/java/com/skhuthon/caffeinebalance/caffeine/controller/ProductController.java
  src/main/java/com/skhuthon/caffeinebalance/caffeine/domain/Product.java
  src/main/java/com/skhuthon/caffeinebalance/caffeine/dto/request/ProductRequestDTO.java
  src/main/java/com/skhuthon/caffeinebalance/caffeine/dto/response/ProductResponseDTO.java
  src/main/java/com/skhuthon/caffeinebalance/caffeine/repository/ProductRepository.java
  src/main/java/com/skhuthon/caffeinebalance/caffeine/service/ProductService.java
  src/main/java/com/skhuthon/caffeinebalance/mainpage/controller/MainPageController.java
  src/main/java/com/skhuthon/caffeinebalance/mainpage/domain/MainPageCaffeineIntake.java
  src/main/java/com/skhuthon/caffeinebalance/mainpage/dto/request/MainPageRequestDTO.java
  src/main/java/com/skhuthon/caffeinebalance/mainpage/dto/response/MainPageResponseDTO.java
  src/main/java/com/skhuthon/caffeinebalance/mainpage/repository/MainPageCaffeineIntakeRepository.java
  src/main/java/com/skhuthon/caffeinebalance/mainpage/service/MainPageService.java
  src/main/java/com/skhuthon/caffeinebalance/user/domain/User.java
  src/main/java/com/skhuthon/caffeinebalance/user/dto/response/UserCaffeineResponseDTO.java
  src/main/java/com/skhuthon/caffeinebalance/user/dto/response/UserResponseDTO.java
  src/test/java/com/skhuthon/caffeinebalance/CaffeineDTOBalanceApplicationTests.java
Labels: feature

#34 [fix] skipUrl 수정
  src/main/java/com/skhuthon/caffeinebalance/auth/jwt/JWTFilter.java
Labels: bug

#35 fix: 랜덤 상품 추천 수정
  src/main/java/com/skhuthon/caffeinebalance/Product/controller/ProductController.java
  src/main/java/com/skhuthon/caffeinebalance/Product/dto/response/ProductResponseDTO.java
  src/main/java/com/skhuthon/caffeinebalance/Product/repository/ProductRepository.java
  src/main/java/com/skhuthon/caffeinebalance/Product/service/ProductService.java
  src/main/java/com/skhuthon/caffeinebalance/auth/config/CorsMvcConfig.java
  src/main/java/com/skhuthon/caffeinebalance/user/domain/User.java
  src/main/java/com/skhuthon/caffeinebalance/user/dto/request/UserCreateRequestDTO.java
Labels: bug

#40 [feat] 스케줄링 기능 구현
  src/main/java/com/skhuthon/caffeinebalance/CaffeineBalanceApplication.java
  src/main/java/com/skhuthon/caffeinebalance/global/scheduler/CaffeineResetScheduler.java
  src/main/java/com/skhuthon/caffeinebalance/user/domain/User.java
Labels: feature

#42 [fix] 카페인 정보 수정 오류 해결
  src/main/java/com/skhuthon/caffeinebalance/global/exception/CustomException.java
  src/main/java/com/skhuthon/caffeinebalance/global/exception/CustomExceptionHandler.java
  src/main/java/com/skhuthon/caffeinebalance/global/exception/ErrorCode.java
  src/main/java/com/skhuthon/caffeinebalance/global/exception/ErrorResponse.java
  src/main/java/com/skhuthon/caffeinebalance/product/controller/ProductController.java
  src/main/java/com/skhuthon/caffeinebalance/product/domain/Product.java
  src/main/java/com/skhuthon/caffeinebalance/product/dto/request/ProductRequestDTO.java
  src/main/java/com/skhuthon/caffeinebalance/product/dto/response/ProductResponseDTO.java
  src/main/java/com/skhuthon/caffeinebalance/product/repository/ProductRepository.java
  src/main/java/com/skhuthon/caffeinebalance/product/service/ProductService.java
  src/main/java/com/skhuthon/caffeinebalance/user/domain/User.java
  src/main/java/com/skhuthon/caffeinebalance/user/dto/request/UserCreateRequestDTO.java
  src/main/java/com/skhuthon/caffeinebalance/user/dto/response/UserCaffeineResponseDTO.java
  src/main/java/com/skhuthon/caffeinebalance/user/dto/response/UserResponseDTO.java
  src/main/java/com/skhuthon/caffeinebalance/user/service/UserService.java
  src/main/resources/application.yml
Labels: chore, bug, remove

#44 [refactor] 코드 리펙토링
  src/main/java/com/skhuthon/caffeinebalance/auth/jwt/JWTUtil.java
  src/main/java/com/skhuthon/caffeinebalance/global/exception/ErrorResponse.java
  src/main/java/com/skhuthon/caffeinebalance/global/scheduler/CaffeineResetScheduler.java
  src/main/java/com/skhuthon/caffeinebalance/user/controller/UserController.java
  src/main/java/com/skhuthon/caffeinebalance/user/dto/request/UserCreateRequestDTO.java
  src/main/java/com/skhuthon/caffeinebalance/user/dto/response/JwtUserResponseDTO.java
  src/main/java/com/skhuthon/caffeinebalance/user/repository/UserRepository.java
Labels: chore, remove

#45 [feat]: 사용자 정보 조회에서 먹은 음료 조회 기능 추가
  src/main/java/com/skhuthon/caffeinebalance/global/scheduler/CaffeineResetScheduler.java
  src/main/java/com/skhuthon/caffeinebalance/product/controller/ProductController.java
  src/main/java/com/skhuthon/caffeinebalance/product/domain/Product.java
  src/main/java/com/skhuthon/caffeinebalance/product/dto/response/ProductResponseDTO.java
  src/main/java/com/skhuthon/caffeinebalance/product/service/ProductService.java
  src/main/java/com/skhuthon/caffeinebalance/user/domain/User.java
  src/main/resources/application.yml
Labels: feature, chore
